{%- if values.enableConnectivityLink and values.authModel === "apikey" %}
apiVersion: v1
kind: Secret
metadata:
  name: ${{values.vmName}}-apikey-demo
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.vmName}}
    kuadrant.io/apikey: "true"
    authorino.kuadrant.io/managed-by: authorino
    secret.kuadrant.io/plan-id: basic
    backstage.io/kubernetes-id: ${{values.uniqueName}}
type: Opaque
stringData:
  api_key: "${{values.vmName}}-demo-key"
{%- endif %}
