{%- if values.enableConnectivityLink and values.authModel === "apikey" %}
apiVersion: extensions.kuadrant.io/v1alpha1
kind: PlanPolicy
metadata:
  name: ${{values.vmName}}-plans
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.vmName}}
    app.kubernetes.io/name: ${{values.vmName}}
    backstage.io/kubernetes-id: ${{values.uniqueName}}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ${{values.vmName}}-route
  plans:
    - tier: free
      predicate: |
        has(auth.identity) && auth.identity.metadata.annotations["secret.kuadrant.io/plan-id"] == "free"
      limits:
        daily: 100
        custom:
          - limit: 10
            window: "1m"
    - tier: basic
      predicate: |
        has(auth.identity) && auth.identity.metadata.annotations["secret.kuadrant.io/plan-id"] == "basic"
      limits:
        daily: 1000
        custom:
          - limit: 60
            window: "1m"
    - tier: pro
      predicate: |
        has(auth.identity) && auth.identity.metadata.annotations["secret.kuadrant.io/plan-id"] == "pro"
      limits:
        daily: 10000
        custom:
          - limit: 300
            window: "1m"
{%- endif %}
