apiVersion: v1
kind: Service
metadata:
  name: ${{values.vmName}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.vmName}}
    backstage.io/kubernetes-id: ${{values.uniqueName}}
spec:
  selector:
    kubevirt.io/domain: ${{values.vmName}}
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
{%- if values.enableConnectivityLink %}
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
{%- endif %}
  type: ClusterIP
