apiVersion: v1
kind: Secret
metadata:
  name: ${{values.vmName}}-ssh-pubkey
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.vmName}}
type: Opaque
stringData:
  key: ${{values.sshPublicKey}}
