apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${{values.vmName}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.vmName}}
    app.kubernetes.io/part-of: ${{values.vmName}}
    app.kubernetes.io/managed-by: argocd
    vm.kubevirt.io/template: rhel9-server
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    description: ${{values.description}}
spec:
  runStrategy: ${{values.runStrategy}}
  template:
    metadata:
      labels:
        kubevirt.io/domain: ${{values.vmName}}
        app: ${{values.vmName}}
        app.kubernetes.io/part-of: ${{values.vmName}}
    spec:
      domain:
        cpu:
          cores: ${{values.cpuCores}}
          sockets: ${{values.cpuSockets}}
          threads: ${{values.cpuThreads}}
        memory:
          guest: ${{values.memory}}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - name: ssh
                  port: 22
                  protocol: TCP
{%- if values.enableConnectivityLink %}
                - name: http
                  port: 8080
                  protocol: TCP
{%- endif %}
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: ${{values.vmName}}-rootdisk
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: ${{values.vmName}}-cloudinit
  dataVolumeTemplates:
    - metadata:
        name: ${{values.vmName}}-rootdisk
      spec:
        storage:
          resources:
            requests:
              storage: ${{values.rootDiskSize}}
{%- if values.storageClass %}
          storageClassName: ${{values.storageClass}}
{%- endif %}
        source:
{%- if values.bootSource === "registry" %}
          registry:
            url: "docker://${{values.registryUrl}}"
            pullMethod: node
{%- elif values.bootSource === "bootc-image" %}
          registry:
            url: "docker://${{values.bootcImageUrl}}"
            pullMethod: node
{%- endif %}
